import product1 from "../../images/product1.svg";

const ProductData = [
  {
    id: "P1",
    image: product1,
    title: "Lorem ipsum dolor sit.",
    ratings: "****",
    originalPrice: "₹400",
    afterDiscountPrice: "200",
    discount: "50% off",
    count: 1,
  },
  {
    id: "P2",
    image: product1,
    title: "Lorem ipsum dolor sit.",
    ratings: "****",
    originalPrice: "₹400",
    afterDiscountPrice: "200",
    discount: "50% off",
    count: 1,
  },
  {
    id: "P3",
    image: product1,
    title: "Lorem ipsum dolor sit.",
    ratings: "****",
    originalPrice: "₹400",
    afterDiscountPrice: "200",
    discount: "50% off",
    count: 1,
  },
  {
    id: "P4",
    image: product1,
    title: "Lorem ipsum dolor sit.",
    ratings: "****",
    originalPrice: "₹400",
    afterDiscountPrice: "200",
    discount: "50% off",
    count: 1,
  },
  {
    id: "P5",
    image: product1,
    title: "Lorem ipsum dolor sit.",
    ratings: "****",
    originalPrice: "₹400",
    afterDiscountPrice: "200",
    discount: "50% off",
    count: 1,
  },
  {
    id: "P6",
    image: product1,
    title: "Lorem ipsum dolor sit.",
    ratings: "****",
    originalPrice: "₹400",
    afterDiscountPrice: "200",
    discount: "50% off",
    count: 1,
  },
  {
    id: "P7",
    image: product1,
    title: "Lorem ipsum dolor sit.",
    ratings: "****",
    originalPrice: "₹400",
    afterDiscountPrice: "200",
    discount: "50% off",
    count: 1,
  },
  {
    id: "P8",
    image: product1,
    title: "Lorem ipsum dolor sit.",
    ratings: "****",
    originalPrice: "₹400",
    afterDiscountPrice: "200",
    discount: "50% off",
    count: 1,
  },
  {
    id: "P9",
    image: product1,
    title: "Lorem ipsum dolor sit.",
    ratings: "****",
    originalPrice: "₹400",
    afterDiscountPrice: "200",
    discount: "50% off",
    count: 1,
  },
  {
    id: "P10",
    image: product1,
    title: "Lorem ipsum dolor sit.",
    ratings: "****",
    originalPrice: "₹400",
    afterDiscountPrice: "200",
    discount: "50% off",
    count: 1,
  },
  {
    id: "P11",
    image: product1,
    title: "Lorem ipsum dolor sit.",
    ratings: "****",
    originalPrice: "₹400",
    afterDiscountPrice: "200",
    discount: "50% off",
  },
  {
    id: "P12",
    image: product1,
    title: "Lorem ipsum dolor sit.",
    ratings: "****",
    originalPrice: "₹400",
    afterDiscountPrice: "200",
    discount: "50% off",
    count: 1,
  },
];

export { ProductData };
